const assert = require('node:assert/strict')
const test = require('node:test')
const path = require('node:path')
const load = require('../../scripts/test-utils/load-ts-module')
const create = () => load(path.resolve('src/common/performance/settingsDraft.ts')).createSettingsDraft({ a: 1, b: 2 })

test('draft applies only edited fields and adopts unrelated external changes', () => {
  const draft = create()
  draft.set('a', 3)
  draft.sync({ a: 1, b: 4 })
  assert.deepEqual(draft.patch(), { a: 3 })
  assert.equal(draft.values.b, 4)
  draft.reset()
  assert.deepEqual(draft.values, { a: 1, b: 4 })
  assert.deepEqual(draft.patch(), {})
})
test('concurrent edits require confirmation and preserve the user draft', () => {
  const draft = create()
  draft.set('a', 3)
  draft.sync({ a: 5, b: 2 })
  assert.deepEqual(draft.conflicts(), ['a'])
  assert.equal(draft.values.a, 3)
  draft.set('a', 3)
  assert.deepEqual(draft.conflicts(), [])
  draft.sync({ a: 3, b: 2 })
  assert.deepEqual(draft.patch(), {})
})
